sudo: false
language: python
python:
- '3.6'
before_script:
- pip install -e .
- pip install pycodestyle
- pip install nose2
- pip install coverage
- pip install commonconf
- pip install coveralls
script:
- pycodestyle uw_zoom/
- coverage run uw_zoom/test.py -v
after_script:
- coveralls
before_deploy:
- find uw_zoom/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > uw_zoom/VERSION
deploy:
  provider: pypi
  user: uw-it-aca
  skip_cleanup: true
  password:
    secure: POyciEF7RSJ25esk2is8vAHPnXUDEvXbrucoNTRDEcrMZ9CU4gDhS6GrI+VRasxXxfYAeehqCtV8Lxb9l6WDEBk0l8A0aDVnTuraHbPU9xOf6zHEPlXZNeYIiXk36HrR/hD0xFl31POmRmQBdFnfoetdjBpccrGTvIS+taCXDw4GJ64JuLWe7YAG7siMycmpjqa4ivsxiFkZHRHYol9Q6T4UhoRmX9h4c9GiKap6LRmfXTQZEylnlrsib2Z2SaJZcqUCyLMt63rSMj4KorKxpobGKyhf/+7U2ERxXFhpRy9SR4Glq2le09mg933Efd+XyzMjYX3vRATEeoQZnqPWE8rhCWTRFHiKV6pQ1D9uMc0F69Fu/bEy2yna1rsMF23wMt9uWWgaXf3QiL/aC8tlF5Ujt7ENJrpha72TZaUjLNsJY54VxS2qXpvHQP0hYOU1r/xgE5vKlpRuk64Le3ObnX0iJTXbOLoZJO8c0jj/kPHq7S3Nffnx5UPE08l0NNIy5ySxUy8jQLgaqnKML3D7AIZI8VuIj51Lx+x087jy49k7LvzuJS5JIsE9jkRl5zeXtBIIkTRtEKXudhrh89oxBTq9wVkIU775aVzXLWt+GVatNa9fCHfzuwFGzN0WUVCNf+LzeI2yoDvukC6j4hykneQmu40ovj21oOtqLGJyJqI=
  on:
    tags: true
    python: '3.6'
