sudo: false
language: python
python:
- '3.6'
before_script:
- pip install -e .
- pip install pycodestyle
- pip install nose2
- pip install coverage
- pip install commonconf
- pip install coveralls
script:
- pycodestyle uw_zoom/
- coverage run uw_zoom/test.py -v
after_script:
- coveralls
before_deploy:
- find uw_zoom/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > uw_zoom/VERSION
deploy:
  provider: pypi
  user: uw-it-aca
  skip_cleanup: true
  password:
    secure: RlDsDXqrYefmJh00bqRXepy+vOE3qbS1EiRsxh5KpJfHN5gbBTRpOYxDVYqoFbusLCk8psxmxHg0riIYCeF9NE3ubj1GOQDUgApNp3VqU0Q21SvQlUcGRE1wk+8P9NMGlVnQmRPEmailIWE/wjbbtF9PnuLSq+nqAM4GkxcRc/sah3Wvl+20IhGxY+8mdKDx4TSh9qkQei4qNBB8aHP30QSuklz+pX0F8v2ZZg3JOCwret/Rny+KQY0s2xwXWP6UN0vrTlISy8aasdcuH2NuXGg7lWkDGS925/+yshmFy9ZAtk9pQBo65EKSsTaqdKj+xKu5u4ajVG9hoGWNg9I3OIa8wFljQ9c5zHWtXUlrOhm7cBXClErf3pbUQ3KGtJQyRlTC251QOJkyd4iY0qhm0mbelpfbOJhrVLDE2+bpk+ewnK8UWVGiDirRGthUxvaq5QaBxG+EGyLB3b3Oob7PEF+dYUgEzHoRWzLyv5dBQupYIPkPW0MdJVafLB4mU2RkLlhaUjiM/meF4bnD1K6Jjif4WA8PugfIGfDwLc/e+Ctp5dkCr5Y3uIXcYbgZtYnicWIP0SAlW4DzqnA6HMAfShPcthhRVfmP8onahLieuWzrPL9vTwwM2nQBK6cCEXWDo2nCTD9nZOKubgcEArCjUCjdMmzlQub9P/yfllLp7NQ=
  on:
    tags: true
    python: '3.6'
