sudo: false
language: python
python:
- '3.6'
before_script:
- pip install -e .
- pip install pycodestyle
- pip install nose2
- pip install coverage
- pip install commonconf
- pip install coveralls
script:
- pycodestyle uw_zoom/
- coverage run uw_zoom/test.py -v
after_script:
- coveralls
before_deploy:
- find uw_zoom/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > uw_zoom/VERSION
deploy:
  provider: pypi
  user: uw-it-aca
  skip_cleanup: true
  password:
    secure: B1zoLqpli6tAarJ7T9BDEkBncBznArGmJ5MrWi9OXmbvuGFYJj270vYMprB8NBQpoXLkgcX6nAWUU7TEd1IZ/HZ59llpJMYRRrk+6S0p5cuDwKPyvRB9bn352b1d1Gz+LPi9qGHIb6/zxAMBUlub9ffK/+7f0td1vjEmhD5YM1sHpVRw0J81kgviA8sUtYBjTzibRlopygOsEuPzklFEWRVyCcq4WrQSWmvk1M9vOGrGlK63DpVB6T65QM1NOXpwui/d6BzRub4Jaz+8bVSmG4Y7iiwMX8khYaRWFV1m5ZWn3Aw7RRetXgrkzmwhx6+5DyFd3qiHgFvA2Jlu8RE3+w1mH2fJ4/4VcBfPNH0PAtyTS7Z5adjdy4YQU+sYbkE3Ps/IJYPDmYWffdcr4o3fly6SWUnJs6cGJZ2q+9hkgRa75QQoQ4RoNC/xEXlIVG9gWdByObyH/vpQp48Vui79RXNIbAytsMQe9Y982EqD4WBe95SPk3ZxWUdWn2+FbKZEa5q4A8QR5iZ7hfIx9X0fcfYFs3wCpajvc+iQCRpwi9TeD4incRFi9BkHlQ08yQW4qRxLBM2NCTzuwo57GoB2je9H2LXngc/ZSU2mTYoe6t3xZTzb/rsCsLtNMXKrE4hJWHHPG9HFgfE7XIqUz3Rpz3+x9QqWv07WJMCcj9Oxa4c=
  on:
    tags: true
    python: '3.6'
